"""Generate the model card from committed metrics + bundle provenance.

The card is a derived artifact: every number is rendered from
results/metrics.json and the model bundle, so the card cannot drift from
the measured evaluation. Regenerated by the ``model_card`` Snakefile
rule whenever metrics change.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib

from comp_tox.util import load_config


def render_card(metrics: dict, bundle: dict, cfg: dict) -> str:
    m = metrics["models"][metrics["primary_model"]]
    ad = m["applicability_domain"]
    cf = m["conformal"]
    counts = metrics["counts"]
    others = {
        k: v for k, v in metrics["models"].items() if k != metrics["primary_model"]
    }
    boot = metrics.get("bootstrap", {})

    def ci(key: str) -> str:
        lo, hi = m.get(key) or (None, None)
        return f"[{lo:.3f}, {hi:.3f}]" if lo is not None else "unavailable"

    lines = [
        f"# Model card: {metrics['endpoint']} activity classifier",
        "",
        "Generated from the committed metrics and the trained model bundle by",
        "`comp_tox.serve.modelcard`. Every number below is a measured artifact.",
        "",
        "## Model",
        "",
        f"- Primary: `{metrics['primary_model']}` on Morgan fingerprints",
        f"  (`{bundle.get('fingerprint')}`), Platt-calibrated on validation scaffolds",
        f"- Compared on identical scaffold splits: "
        + ", ".join(f"`{k}`" for k in others),
        f"- Trained on {counts['train']} compounds "
        f"({counts['train_actives']} actives, prevalence "
        f"{counts['train_prevalence']:.3f}). Evaluated on {counts['test']} "
        f"held-out scaffolds ({counts['test_actives']} actives)",
        "",
        "## Intended use",
        "",
        f"Research-grade prioritization signal for Tox21 {metrics['endpoint']}.",
        "Not a regulatory determination, not a safety",
        "assessment, not validated for clinical or GxP use. Compounds",
        "flagged out-of-domain carry weaker measured performance (see below).",
        "",
        "## Scaffold-split test performance",
        "",
        f"- AUROC {m['auroc']:.3f} (95% CI {ci('auroc_ci95')})",
        f"- AUPRC {m['auprc']:.3f} (95% CI {ci('auprc_ci95')}, prevalence "
        f"{counts['test_prevalence']:.3f})",
        f"- ECE {m['ece']:.3f} (Platt-calibrated on validation scaffolds)",
        "",
    ]
    if boot.get("status") == "withdrawn":
        lines += [
            f"Bootstrap CIs are withdrawn for this run: {boot['reason']}",
            "",
        ]
    lines += [
        "## Uncertainty and applicability domain",
        "",
        f"- Split-conformal at alpha={cf['alpha']}: coverage {cf['coverage']:.3f},",
        f"  mean set size {cf['mean_set_size']:.2f}, qhat {cf['qhat']:.3f}",
        f"- AD (Tanimoto nn <= {ad['threshold']}): {ad['in_domain_fraction']:.3f} "
        "of the eval set is in-domain.",
        f"  In-domain AUROC {ad['in_domain']['auroc']:.3f} vs. out-domain "
        f"{ad['out_domain']['auroc']:.3f}. Conformal coverage holds "
        f"({ad['conformal_coverage_in_domain']:.3f} in / "
        f"{ad['conformal_coverage_out_domain']:.3f} out).",
        "",
        "## Serving and monitoring",
        "",
        "`comp_tox.serve.app` exposes /predict (probability + conformal set +",
        "AD flag) and /drift (batch shift vs. the frozen train reference",
        "across nn-distance, bit-frequency JS divergence, and predicted-",
        "positive rate). Drift warnings mean the measured metrics above",
        "stop applying to that batch.",
        "",
        "## Provenance",
        "",
        f"- features sha256 `{bundle.get('features_sha256', '')[:12]}...`, "
        f"splits sha256 `{bundle.get('splits_sha256', '')[:12]}...`",
        f"- fingerprint `{bundle.get('fingerprint')}`, split seed "
        f"{cfg['split']['seed']}, conformal alpha {cfg['evaluation']['conformal_alpha']}",
        "- Upstream data: EPA Tox21 (deepchem mirror); models: scikit-learn",
        "  logistic regression / random forest, PyG GIN, TF/Keras MLP.",
        "",
        "## Limitations",
        "",
        "- Single endpoint, single public dataset. No prospective validation.",
        "- In-domain fraction is low on held-out scaffolds; treat",
        "  out-of-domain predictions as triage signals only.",
        "- Conformal coverage is marginal, not conditional on chemotype.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    metrics = json.load(open(sys.argv[1]))
    bundle = joblib.load(sys.argv[2])
    out = Path(sys.argv[3])
    out.write_text(render_card(metrics, bundle, load_config()))
    print(f"model_card: -> {out}")


if __name__ == "__main__":
    main()
